#!/usr/bin/env bash

# shellcheck disable=SC2044

echo "Searching for old version index files"
for FILE_INDEX in $(find /usr/lib/node_modules ./node_modules -type f -name 'index-v*.js'); do
	FILE_V8="${FILE_INDEX/v.*.\.js/v8\.js/}"
	FILE_V9="${FILE_INDEX/v.*.\.js/v9\.js/}"
	FILE_V10="${FILE_INDEX/v.*.\.js/v10\.js/}"
	FILE_V11="${FILE_INDEX/v.*.\.js/v11\.js/}"
	FILE_V12="${FILE_INDEX/v.*.\.js/v12\.js/}"
	FILE_V13="${FILE_INDEX/v.*.\.js/v13\.js/}"

	echo "FILE_INDEX : '${FILE_INDEX}'"
	echo "FILE_V8    : '${FILE_V8}'"
	echo "FILE_V9    : '${FILE_V9}'"
	echo "FILE_V10   : '${FILE_V10}'"
	echo "FILE_V11   : '${FILE_V11}'"
	echo "FILE_V12   : '${FILE_V12}'"
	echo "FILE_V13   : '${FILE_V13}'"

	[[ ! -s "${FILE_V8}"  ]] && cp -fv "${FILE_INDEX}" "${FILE_V8}"
	[[ ! -s "${FILE_V9}"  ]] && cp -fv "${FILE_INDEX}" "${FILE_V9}"
	[[ ! -s "${FILE_V10}" ]] && cp -fv "${FILE_INDEX}" "${FILE_V10}"
	[[ ! -s "${FILE_V11}" ]] && cp -fv "${FILE_INDEX}" "${FILE_V11}"
	[[ ! -s "${FILE_V12}" ]] && cp -fv "${FILE_INDEX}" "${FILE_V12}"
	[[ ! -s "${FILE_V13}" ]] && cp -fv "${FILE_INDEX}" "${FILE_V13}"

	echo; echo
done

exit 0
