#!/usr/bin/env bash

ARRAY_LINK=(
'callers-path'
'defaults-deep'
'express'
'json-socket'
'jsonfile'
'object-path'
'performance-now'
'socket.io'
'trucolor'
)

npm -g i "${ARRAY_LINK[@]}" --unsafe-perm

npm link "${ARRAY_LINK[@]}"
